"""add_user_engagement_fields

Revision ID: 6970232cbba5
Revises: 7509e526ce74
Create Date: 2026-04-15 22:40:07.568052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6970232cbba5'
down_revision: Union[str, Sequence[str], None] = '7509e526ce74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_pro', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('streak_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('scan_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('referrals_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'referrals_count')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'scan_count')
    op.drop_column('users', 'badges')
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'streak_count')
    op.drop_column('users', 'is_pro')
    # ### end Alembic commands ###
