"""Initial migration

Revision ID: 7509e526ce74
Revises: 
Create Date: 2026-03-31 15:49:05.150416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7509e526ce74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulation', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('is_elective', sa.Boolean(), nullable=True),
    sa.Column('elective_vertical', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_branch'), 'curriculum', ['branch'], unique=False)
    op.create_index(op.f('ix_curriculum_id'), 'curriculum', ['id'], unique=False)
    op.create_index(op.f('ix_curriculum_regulation'), 'curriculum', ['regulation'], unique=False)
    op.create_index(op.f('ix_curriculum_subject_code'), 'curriculum', ['subject_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('regulation', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('total_credits', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('original_semester', sa.Integer(), nullable=True),
    sa.Column('is_arrear', sa.Boolean(), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_subject_code'), 'subjects', ['subject_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_subject_code'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_curriculum_subject_code'), table_name='curriculum')
    op.drop_index(op.f('ix_curriculum_regulation'), table_name='curriculum')
    op.drop_index(op.f('ix_curriculum_id'), table_name='curriculum')
    op.drop_index(op.f('ix_curriculum_branch'), table_name='curriculum')
    op.drop_table('curriculum')
    # ### end Alembic commands ###
