"""Add applied_referral_code to User

Revision ID: 7be26c6ebde7
Revises: 6970232cbba5
Create Date: 2026-04-18 12:50:17.809168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be26c6ebde7'
down_revision: Union[str, Sequence[str], None] = '6970232cbba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('applied_referral_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'applied_referral_code')
    # ### end Alembic commands ###
